/* Basket Action Types*/

export const ADD_TO_BASKET = "ADD_TO_BASKET"

export const CHANGE_CURRENCY = "CHANGE_CURRENCY"
export const CHANGE_BACKGROUND = "CHANGE_BACKGROUND"

export const DELETE_FROM_BASKET = "DELETE_FROM_BASKET"